apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ecommerce-dev
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8700
      targetPort: 8700
  type: ClusterIP