# k8s/proxy-client/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  labels:
    app: proxy-client
spec:
  type: ClusterIP
  ports:
  - port: 8900
    targetPort: 8900
    protocol: TCP
    name: http
  selector:
    app: proxy-client