apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: selimhorri/order-service-ecommerce-boot:0.1.0
          ports:
            - containerPort: 8300
          envFrom:
            - configMapRef:
                name: app-config